apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: all-applicationsets
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/ggorockee/devops-camping.git
      revision: HEAD
      files:
      - path: "argocd/applicationsets/config/dev/*-app.yaml"

  template:
    metadata:
      name: '{{appname}}'
    spec:
      project: '{{project}}'
      sources:
      - repoURL: '{{repoURL}}'
        chart: '{{chartName}}'
        targetRevision: '{{chartVersion}}'
        helm:
          valueFiles:
            - "$values/helm-values/{{env}}/{{appname}}/values.yaml"
      - repoURL: https://github.com/ggorockee/devops-camping.git
        targetRevision: HEAD
        ref: values

      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true