apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: all-istio-gateway
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/ggorockee/devops-camping.git
      revision: main
      files:
      - path: "argocd/applicationsets/config/dev/service-mesh/*.yaml"

  template:
    metadata:
      name: '{{appname}}-service-mesh'
    spec:
      project: '{{project}}'
      sources:
      - repoURL: '{{repoURL}}'
        chart: '{{chartName}}'
        targetRevision: '{{chartVersion}}'
        helm:
          valueFiles:
            - "$values/helm-values/{{env}}/service-mesh/{{ref}}-values.yaml"
      - repoURL: https://github.com/ggorockee/devops-camping.git
        targetRevision: main
        ref: values

      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true