nameOverride: ''
fullnameOverride: ''
deployment:
  replicaCount: 1
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  podAnnotations: {}
  podLabels: {}
  image:
    repository: ggorockee/camping-backend-with-go
    pullPolicy: IfNotPresent
    tag: v-05628ada
  imagePullSecrets: []
  podSecurityContext: {}
  securityContext: {}
  livenessProbe:
    httpGet:
      path: /v1/healthcheck
      port: fiber
  readinessProbe:
    httpGet:
      path: /v1/healthcheck
      port: fiber
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ''
service:
  type: ClusterIP
  ports:
    - port: 3000
      containerPort: 3000
      name: fiber
      protocol: ''
volumes: []
volumeMounts: []
